## Heart Section

Dataset Link : https://www.kaggle.com/datasets/noeyislearning/framingham-heart-study

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/Medical_Disease_NN/framingham_heart_study.csv")

In [3]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [5]:
feature = df.drop("TenYearCHD", axis=1)
target = df["TenYearCHD"]

In [6]:
feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
dtypes: float64(9), int64(6)
memory usage: 497.0 KB

In [7]:
target.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4240 entries, 0 to 4239
Series name: TenYearCHD
Non-Null Count  Dtype
--------------  -----
4240 non-null   int64
dtypes: int64(1)
memory usage: 33.3 KB

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    feature,
    target,
    test_size=0.2,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42
)

In [9]:
print(X_train.shape)
print(X_temp.shape)
print(X_val.shape)
print(X_test.shape)

#80% of X_train, 20% X_temp, 10% X_val and 10% X_test

(3392, 15)
(848, 15)
(424, 15)
(424, 15)

In [10]:
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

num_cols = X_train.select_dtypes(exclude=["object"]).columns

num_pipeline = make_pipeline(SimpleImputer(strategy = "median"), StandardScaler())

preprocess = ColumnTransformer(
    [
        ("num", num_pipeline, num_cols)
    ]
)

inputs = preprocess.fit_transform(X_train)
vals = preprocess.transform(X_val)
test = preprocess.transform(X_test)

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
# class Heart_disease(tf.keras.Model):
#   def __init__(self,units=30,activation="relu", **kwargs):
#     super().__init__(**kwargs)
#     self.input_wide_norm = tf.keras.layers.Normalization()
#     self.input_deep_norm = tf.keras.layers.Normalization()
#     self.hidden1 = tf.keras.layers.Dense(units, activation=activation)
#     self.hidden2 = tf.keras.layers.Dense(units, activation=activation)
#     self.hidden3 = tf.keras.layers.Dense(units, activation=activation)
#     self.output_layer = tf.keras.layers.Dense(1, activation="sigmoid")

#   def call(self, inputs):
#     input_wide, input_deep = inputs
#     norm_wide = self.input_wide_norm(input_wide)
#     norm_deep = self.input_deep_norm(input_deep)
#     hidden1 = self.hidden1(norm_deep)
#     hidden2 = self.hidden2(hidden1)
#     hidden3 = self.hidden3(hidden2)
#     concat = tf.keras.layers.concatenate([norm_wide, hidden3])
#     output_layer = self.output_layer(concat)
#     return output_layer

# model = Heart_disease(30,activation="relu", name = "heart_disease_model")
# model.input_wide_norm.adapt(inputs)
# model.input_deep_norm.adapt(inputs)

# model.compile(
#     optimizer=tf.keras.optimizers.Adam(1e-3),
#     loss="binary_crossentropy",
#     metrics=[
#         "accuracy",
#         tf.keras.metrics.AUC(name="auc")
#     ]
# )

# checkpoint_cb = tf.keras.callbacks.ModelCheckpoint("my_checkpoints.weights.h5", save_weights_only=True)

# early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)

In [13]:
%pip install -q -U tensorboard-plugin-profile

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 27.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.2/109.2 kB 3.5 MB/s eta 0:00:00

In [14]:
# from pathlib import Path
# from time import strftime

# def get_run_logdir(root_logdir="Heart_Disease_Logs"):
#     return Path(root_logdir) / strftime("run_%Y_%m_%d_%H_%M_%S")

# run_logdir = get_run_logdir()

# tensorboard_cb = tf.keras.callbacks.TensorBoard(run_logdir, profile_batch=(100,200))

In [15]:
# history = model.fit(
#     (inputs, inputs),
#     y_train,
#     validation_data=((vals, vals), y_val),
#     epochs=20,
#     callbacks=[checkpoint_cb, early_stopping_cb, tensorboard_cb]
# )

In [16]:
%load_ext tensorboard
# %tensorboard --logdir=./Heart_Disease_Logs

In [17]:
%pip install -q -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.5 MB/s eta 0:00:00

In [18]:
# import keras_tuner as kt

# def build_model(hp):
#   n_hidden = hp.Int("n_hidden", min_value = 0, max_value = 8, default = 2)
#   n_neuron = hp.Int("n_neuron", min_value = 18, max_value = 256)
#   learning_rate = hp.Float("learning_rate", min_value = 1e-4, max_value = 1e-2, sampling = "log")
#   optimizer = hp.Choice("optimizer", values = ["sgd", "adam"])
#   if optimizer == "sgd":
#     optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)
#   else:
#     optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

# class MyClassificationHyperMOdel(kt.HyperModel):
#   def build(self, hp):
#     return build_model(hp)

#   def fit(self, hp, model, X, y, **kwargs):
#     if hp.Boolean("normalize"):
#       norm_layer = tf.keras.layers.Normalization()
#       X = norm_layer(input_wide)

In [19]:
class Heart_disease(tf.keras.Model):

    def __init__(self, n_hidden, units, activation="relu", **kwargs):
        super().__init__(**kwargs)

        self.input_wide_norm = tf.keras.layers.Normalization()
        self.input_deep_norm = tf.keras.layers.Normalization()

        # Variable number of hidden layers
        self.hidden_layers = [
            tf.keras.layers.Dense(units, activation=activation)
            for _ in range(n_hidden)
        ]

        self.output_layer = tf.keras.layers.Dense(
            1,
            activation="sigmoid"
        )

    def call(self, inputs):

        input_wide, input_deep = inputs

        norm_wide = self.input_wide_norm(input_wide)
        x = self.input_deep_norm(input_deep)

        for layer in self.hidden_layers:
            x = layer(x)

        concat = tf.keras.layers.concatenate([norm_wide, x])

        return self.output_layer(concat)

In [20]:
def build_model(hp):

    # Hyperparameters
    n_hidden = hp.Int(
        "n_hidden",
        min_value=1,
        max_value=8,
        default=3
    )

    units = hp.Int(
        "units",
        min_value=16,
        max_value=256,
        step=16
    )

    activation = hp.Choice(
        "activation",
        values=["relu", "tanh"]
    )

    learning_rate = hp.Float(
        "learning_rate",
        min_value=1e-4,
        max_value=1e-2,
        sampling="log"
    )

    optimizer_name = hp.Choice(
        "optimizer",
        values=["adam", "sgd"]
    )

    if optimizer_name == "adam":
        optimizer = tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        )
    else:
        optimizer = tf.keras.optimizers.SGD(
            learning_rate=learning_rate
        )

    model = Heart_disease(
        n_hidden=n_hidden,
        units=units,
        activation=activation,
        name="heart_disease_model"
    )

    # Adapt Normalization Layers
    model.input_wide_norm.adapt(inputs)
    model.input_deep_norm.adapt(inputs)

    # Build the model by calling it once
    _ = model((inputs[:1], inputs[:1]))

    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=[
            "accuracy",
            tf.keras.metrics.AUC(name="auc")
        ]
    )

    return model

In [21]:
import keras_tuner as kt

hyperband_tuner = kt.Hyperband(

    build_model,

    objective="val_auc",

    max_epochs=20,

    factor=3,

    overwrite=True,

    directory="heart_disease_logs",

    project_name="hyperband"

)

In [22]:
early_stopping_cb = tf.keras.callbacks.EarlyStopping(

    monitor="val_loss",

    patience=5,

    restore_best_weights=True

)

In [23]:
hyperband_tuner.search(

    (inputs, inputs),

    y_train,

    validation_data=((vals, vals), y_val),

    epochs=20,

    callbacks=[early_stopping_cb]

)

Trial 30 Complete [00h 00m 24s]
val_auc: 0.576602578163147

Best val_auc So Far: 0.7332875728607178
Total elapsed time: 00h 04m 28s

In [24]:
best_model = hyperband_tuner.get_best_models(1)[0]

In [25]:
best_hp = hyperband_tuner.get_best_hyperparameters(1)[0]

print(best_hp.values)

{'n_hidden': 8, 'units': 144, 'activation': 'tanh', 'learning_rate': 0.00120643610854765, 'optimizer': 'adam', 'tuner/epochs': 20, 'tuner/initial_epoch': 7, 'tuner/bracket': 1, 'tuner/round': 1, 'tuner/trial_id': '0022'}

In [26]:
loss, accuracy, auc = best_model.evaluate(

    (test, test),

    y_test

)

print(loss)
print(accuracy)
print(auc)

14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8467 - auc: 0.7204 - loss: 0.3881
0.3880864381790161
0.8466981053352356
0.7203535437583923

## Kidney Section

Dataset Link : https://www.kaggle.com/datasets/mansoordaku/ckdisease

In [27]:
df_kidney = pd.read_csv("/content/drive/MyDrive/Datasets/Medical_Disease_NN/kidney_disease.csv")

In [28]:
df_kidney.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [29]:
df_kidney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [30]:
target = df_kidney["classification"]
features = df_kidney.drop("classification", axis =1)

In [31]:
print(features.info())
print(target.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      400 non-null    int64
 1   age     391 non-null    float64
 2   bp      388 non-null    float64
 3   sg      353 non-null    float64
 4   al      354 non-null    float64
 5   su      351 non-null    float64
 6   rbc     248 non-null    object
 7   pc      335 non-null    object
 8   pcc     396 non-null    object
 9   ba      396 non-null    object
 10  bgr     356 non-null    float64
 11  bu      381 non-null    float64
 12  sc      383 non-null    float64
 13  sod     313 non-null    float64
 14  pot     312 non-null    float64
 15  hemo    348 non-null    float64
 16  pcv     330 non-null    object
 17  wc      295 non-null    object
 18  rc      270 non-null    object
 19  htn     398 non-null    object
 20  dm      398 non-null    object
 21  cad     398 non-null    object
 22  appet   399 non-null    object
 23  pe      399 non-null    object
 24  ane     399 non-null    object
dtypes: float64(11), int64(1), object(13)
memory usage: 78.3+ KB
None
<class 'pandas.core.series.Series'>
RangeIndex: 400 entries, 0 to 399
Series name: classification
Non-Null Count  Dtype
--------------  -----
400 non-null    object
dtypes: object(1)
memory usage: 3.3+ KB
None

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(features, target,test_size=0.2, random_state = 42)

X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size = 0.5, random_state = 42)

In [33]:
print(X_train.shape)
print(X_temp.shape)
print(X_test.shape)
print(X_val.shape)

(320, 25)
(80, 25)
(40, 25)
(40, 25)

In [34]:
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

num_cols = X_train.select_dtypes(exclude=["object"]).columns
obj_cols = X_train.select_dtypes(include=["object"]).columns

nums_pipeline = make_pipeline(SimpleImputer(strategy="median"))

cat_pipeline = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore")
    )

preprocess = ColumnTransformer([
    ("nums_pipeline", num_pipeline, num_cols),
    ("cat_pipeline", cat_pipeline, obj_cols),
])

X_train = preprocess.fit_transform(X_train)
X_test = preprocess.transform(X_test)
X_val = preprocess.transform(X_val)

In [35]:
print(X_train.dtype)
print(X_train.nnz)

float64
8000